name: (Disabled) Build and Release Chrome Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and build extension
        run: |
          yarn install
          NODE_ENV=production yarn build

      - name: Package extension
        id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'build'
          zipFilePath: 'build/extension.zip'

      - name: Sign Chrome extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/extension.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'build/extension.crx'
